# Generated by Django 4.2.1 on 2023-05-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_posts", "0002_remove_user_is_admin_remove_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
