# Generated by Django 4.2.1 on 2023-05-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_posts", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
