# Generated by Django 4.2.1 on 2023-05-18 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog_posts", "0004_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="author_id",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author_name",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
