# Generated by Django 4.2.1 on 2023-05-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_posts", "0005_remove_blogpost_author_id_blogpost_author_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="api_author_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
