# Generated by Django 4.2.1 on 2023-05-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_posts", "0006_blogpost_api_author_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="post_url",
            field=models.URLField(max_length=1500, null=True),
        ),
    ]
