# Generated by Django 4.2.1 on 2023-05-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_posts", "0007_blogpost_post_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="body",
            field=models.TextField(max_length=7000),
        ),
    ]
